server:
  port: 8087

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/skeleton
    username: skeleton
    password: skeleton
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 6
  sql:
    init:
      platform: postgresql
  jpa:
    show-sql: true